---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lenovo.
--- DateTime: 2025/2/11 19:15
---   实现对用户秒杀资格的判断
local userId = ARGV[1]
local voucherId = ARGV[2]

local stockKey = 'seckill:stock:' .. voucherId
local voucherOrderKey = 'seckill:order:' .. voucherId

--- 首先判断库存是否充足
if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end


--- 再判断用户是否已经购买过该秒杀券
if (redis.call('sismember', voucherOrderKey, userId) == 1) then
    return 2
end

--- 否则扣减库存，并将userId加入到set中
redis.call('incrby', stockKey, -1)
redis.call('sadd', voucherOrderKey, userId)

return 0

